title: LoForm
description: Lightweight forms for Flutter
baseurl: /lo_form
url: https://YoussefRaafatNasry.github.io
meta_image: https://raw.githubusercontent.com/YoussefRaafatNasry/lo_form/master/website/src/assets/images/preview.png

# Build Settings
destination: ../web/

links:
  github: https://github.com/YoussefRaafatNasry/lo_form
  pub: https://pub.dev/packages/lo_form
  docs: https://docs.page/YoussefRaafatNasry/lo_form

author:
  username: YoussefRaafatNasry
  website: https://YoussefRaafatNasry.github.io
