name: website
description: website app for LoForm.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  example:
    path: ../package/example
  flutter:
    sdk: flutter
  lo_form:
    path: ../package
  universal_html: ^2.0.8

dev_dependencies:

flutter:
  uses-material-design: true
