name: GitHub Pages

on:
  push:
    branches: [master]
    paths:
      - website/**
      - package/example/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install bundler
        run: gem install bundler

      - name: Install gems
        run: bundle
        working-directory: website/src/

      - name: Build Jekyll
        run: bundle exec jekyll build
        working-directory: website/src/

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: 2.5.3

      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          workingDir: website
